name: open_pit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.5.3
  http: ^1.1.2
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  geocode: ^1.0.3
  google_places_flutter: ^2.0.7
  midtrans_sdk: ^0.4.0
  image: ^3.2.2
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  custom_marker: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
